TTT.AddVGUIElement("TTT_ActiveHUD", function(ply)
	local roletext = TTT.GetRoleAsString(ply)

	surface.SetFont("Default")
	surface.SetTextColor(255, 255, 255, 255)
	surface.SetTextPos(128, 100)
	surface.DrawText(" Round time: ".. TTT.GetFormattedRemainingTime())
	surface.SetTextPos(128, 125)
	surface.DrawText("  Your Role: ".. roletext)
	surface.SetTextPos(128, 150)
	surface.DrawText("Round state: ".. TTT.GetFormattedRoundState())
end)